version: 0.2

phases:
  pre_build:
    commands:
      - echo Entrando na fase de pré-construção...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 288761730587.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG="$(git rev-parse --short HEAD)"
      - git clone https://github.com/DarleiQuevedo/Projeto2v2.git
      - ~/.dotnet/dotnet restore #ajuste..
  build:
    commands:
      - echo "Compilando e publicando o aplicativo .NET..."
      - ~/.dotnet/dotnet publish -c Release -o out # ajuste
      - echo Build started on `date`
      - echo Construindo a imagem Docker...
      - docker build -t projeto-2-aws:latest .
      - docker tag projeto-2-aws:latest 288761730587.dkr.ecr.us-east-1.amazonaws.com/projeto-2-aws:latest
  post_build:
    commands:
      - echo "Escrevendo imagem de Arquivo de Definicao imagedefinitions.json..."
      - printf '[{"name":"projeto-2-aws", "imageUri":"288761730587.dkr.ecr.us-east-1.amazonaws.com/projeto-2-aws:latest" } ]' > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Fazendo push da imagem Docker para o ECR...
      - docker push 288761730587.dkr.ecr.us-east-1.amazonaws.com/projeto-2-aws:latest
artifacts:
    files:
      - imagedefinitions.json

