version: 0.2

phases:
  install:
    commands:
      - aws --version
      - echo "Instalando Docker..."
      - echo "yum install docker -y"
  pre_build:
    commands:
      - echo Entrando na fase de pré-construção...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 288761730587.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=288761730587.dkr.ecr.us-east-1.amazonaws.com/projeto-2-aws
      - # git clone https://github.com/DarleiQuevedo/Projeto2v2.git
      - ~/.dotnet/dotnet restore 
  build:
    commands:
      - echo "Compilando e publicando o aplicativo .NET..."
      - ~/.dotnet/dotnet publish -c Release -o out 
      - echo Build started on `date`
      - echo Construindo a imagem Docker...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Escrevendo imagem de Arquivo de Definicao imagedefinitions.json..."
      - printf '[{"name":"projeto-2-aws","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Fazendo push da imagem Docker para o ECR...
      - docker push $REPOSITORY_URI:latest
artifacts:
    files:
      - imagedefinitions.json

